(ns kekkai.node.publisher-parity-test
  "The other end of the netmap boundary: a real envelope, produced by the real
  publisher in `kotoba-lang/kekkai`, read by this repository's verifier.

  Every other test here builds its netmap in the same file that consumes it,
  which proves this code is self-consistent and proves nothing about the format
  the control plane actually emits. Until recently that was moot — nothing
  emitted one, and this agent read an unsigned local file, which the README
  called 'the single most important remaining hole'. `kekkai.envelope` and
  `kekkai.netmap` closed it on the publishing side; this pins that the two
  independently-written implementations agree on bytes.

  `test/fixtures/kekkai-publisher/netmap.signed.edn` is generated by
  `kekkai.fixture-test` over `kekkai.store/demo-data`, and that repository
  asserts it is byte-exactly what its publisher emits. If a change there alters
  key order, integer printing, or namespace-map printing, this test fails here
  rather than a node failing in the field."
  (:require [clojure.string :as str]
            [cljs.reader :as reader]
            [cljs.test :refer [deftest is testing]]
            [kekkai.node.netmap :as netmap]
            [kekkai.node.signed-netmap :as signed]
            ["node:crypto" :as crypto]
            ["node:fs" :as fs]
            ["node:path" :as path]))

(def authority-spki-b64
  "The publisher's Ed25519 SPKI, configured out of band as
   `:netmap-authority-spki-b64`. Deliberately NOT read from the envelope: an
   envelope that carried the only copy of its signer's key would authenticate
   itself."
  "MCowBQYDK2VwAyEADoPY+mKYyjuZSP293WwiRtAEd0dbnol0C8MA4h87S4k=")

(def envelope-text
  (.readFileSync fs (path/join "test" "fixtures" "kekkai-publisher"
                               "netmap.signed.edn")
                 "utf8"))

(deftest a-real-published-envelope-verifies
  (let [nm (signed/verify-envelope envelope-text authority-spki-b64)]
    (testing "it survives this repository's own structural validation"
      (is (= [] (netmap/validate nm)))
      (is (netmap/usable? nm)))
    (testing "and carries the fields the agent binds into the Noise prologue"
      (is (= "kekkai-node/1 tailnet:default netmap:42"
             (netmap/prologue-string nm))))))

(deftest the-published-grants-read-the-same-on-this-side
  (let [nm (signed/verify-envelope envelope-text authority-spki-b64)]
    (testing "the ssh capability the policy opted into survives the crossing"
      (is (netmap/reachable? nm "n-laptop" "n-server" :ssh))
      (is (netmap/permitted? nm "n-laptop" "n-server" :ssh 22)))
    (testing "and does not silently widen"
      (is (not (netmap/permitted? nm "n-laptop" "n-server" :ssh 80)))
      (is (not (netmap/reachable? nm "n-laptop" "n-server" :tun))))
    (testing "the publisher's \"*\" became :any, which is what permitted? tests"
      (is (netmap/permitted? nm "n-laptop" "n-gw" :overlay 9999)))
    (testing "an edged-but-unadmitted peer is present and denied, not absent —
              the distinction the agent logs"
      (let [now 1750000000
            peers (set (map :node/id (:netmap/peers nm)))]
        (is (contains? peers "n-rogue"))
        (is (not (netmap/authorized? (get (netmap/peer-table nm) "n-rogue") now)))
        ;; :status-pending rather than :key-expired — n-rogue's key IS expired,
        ;; but it was never admitted, and the node reports the reason that comes
        ;; first. An operator told "expired" would rotate a key that no
        ;; admission is waiting on.
        (is (= :status-pending
               (:denied (first (filter #(= "n-rogue" (:peer %))
                                       (netmap/denials nm :ssh now))))))))
    (testing "a peer with no edge in either direction was never published"
      (is (not (contains? (set (map :node/id (:netmap/peers nm))) "n-pending"))))
    (testing "and neither was another organization's node"
      (is (empty? (filter #(str/starts-with? (:node/id %) "a-")
                          (:netmap/peers nm)))))))

(deftest dialable-folds-admission-and-the-grant-together
  (let [nm (signed/verify-envelope envelope-text authority-spki-b64)
        now 1750000000
        dialable (set (map (comp :node/id :peer) (netmap/dialable nm :ssh now)))]
    (testing "n-server is admitted AND ssh-granted"
      (is (contains? dialable "n-server")))
    (testing "n-rogue is ssh-granted but expired, so it is not dialable"
      (is (not (contains? dialable "n-rogue"))))
    (testing "n-gw is admitted but has no ssh grant"
      (is (not (contains? dialable "n-gw"))))))

(defn- repayload
  "Rewrite the envelope's payload AND its digest, leaving the signature alone.

  Tampering the payload without fixing the digest would be caught by the digest
  check, which proves nothing about the signature. This produces the envelope an
  attacker who can write the netmap file would actually produce: internally
  consistent, and signed by nobody."
  [text new-payload]
  (let [payload-b64 (.toString new-payload "base64")
        sha (-> (.createHash crypto "sha256") (.update new-payload) (.digest "hex"))
        envelope (reader/read-string text)]
    (pr-str (assoc envelope
                   :netmap/payload-b64 payload-b64
                   :netmap/sha256 sha))))

(deftest a-tampered-published-envelope-is-refused
  (testing "an internally consistent forgery still fails on the signature"
    (let [original (reader/read-string envelope-text)
          payload (.from js/Buffer (:netmap/payload-b64 original) "base64")
          text (.toString payload "utf8")
          moved (.from js/Buffer
                       (str/replace text "\"100.64.0.2\"" "\"100.64.0.99\"")
                       "utf8")]
      (is (not= (.toString moved "utf8") text) "the tamper actually changed something")
      (is (thrown? js/Error
                   (signed/verify-envelope (repayload envelope-text moved)
                                           authority-spki-b64)))))
  (testing "and a different authority refuses a perfectly valid envelope"
    (is (thrown? js/Error
                 (signed/verify-envelope
                  envelope-text
                  "MCowBQYDK2VwAyEAGb9ECWmEzf6FQbrBZ9w7lshQhqowtrbLDFw4rXAxZuE=")))))
